version: '3.9'
services:
  web:
    build: 
      context: ./
      target: dev
    volumes:
      - .:/grupoheredia
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
