import Head from 'next/head'

export default function Layout() {
  return (
    <>

        <title>Grupoheredia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.plyr.io/3.6.12/plyr.css" />

    </>
  )
}